trackedToggles = {
    -- relics
        ["RE01"] = "blood",
        ["RE03"] = "nail",
        ["RE04"] = "shroud",
        ["RE05"] = "linen",
        ["RE07"] = "lung",
        ["RE10"] = "tongues",
    -- rosaries    
        ["RB41"] = "immaculate_bead",
        ["RB105"] = "ruby",
        ["RB203"] = "wheel",
    --prayers
        ["PR01"] = "seguiriya",
        ["PR03"] = "debla",
        ["PR04"] = "saeta",
        ["PR05"] = "companillero",
        ["PR07"] = "lorquiana",
        ["PR08"] = "zarabanda",
        ["PR09"] = "taranto",
        ["PR10"] = "solea",
        ["PR11"] = "tiento",
        ["PR12"] = "cante",
        ["PR14"] = "verdiales",
        ["PR15"] = "romance",
        ["PR16"] = "zambra",
        ["PR101"] = "aubade",
        ["PR201"] = "cantina",
        ["PR202"] = "mirabras",
        ["PR203"] = "tirana",
        --hearts
        ["HE101"] = "dawn",
        ["HE201"] = "apodictic",
        --quest items
        ["QI01"] = "cord",
        ["QI58"] = "key_brother",
        ["QI66"] = "fountain_cloth",
        ["QI67"] = "fountain_hand",
        ["QI68"] = "driedflowers",
        ["QI69"] = "key_secular",
        ["QI70"] = "key_scribe",
        ["QI71"] = "key_inquisitor",
        ["QI72"] = "key_peaks",
        ["QI75"] = "chalice",
        ["QI106"] = "petrified",
        ["QI203"] = "scapular",
        ["QI204"] = "key_wood",
        ["QI301"] = "fourthwound",
        ["CHARGED_1"] = "charge_attack",
        ["RANGED_1"] = "throw_blood",
        ["VERTICAL_1"] = "weight",
        --hosted toggle items
        ["BELL_PUZZLE1_ACTIVATED"] = "statue1",
        ["BELL_PUZZLE2_ACTIVATED"] = "statue2",
        ["BELL_ACTIVATED"] = "bell",
        ["D17Z01_BOSSDEAD"] = "boss_warden",
        ["D08Z01S01_BOSSDEAD"] = "boss_esdras",
        ["D02Z05S01_BOSSDEAD"] = "boss_visage",
        ["D03Z04S01_BOSSDEAD"] = "boss_tres",
        ["D01Z06S01_BOSSDEAD"] = "boss_ten",
        ["D04Z04S01_BOSSDEAD"] = "boss_bishop",
        ["D09Z01S03_BOSSDEAD"] = "boss_quirce",
        ["D05Z01S13_BOSSDEAD"] = "boss_exposito",
        ["D06Z01S25_BOSSDEAD"] = "boss_crisanta",
        ["SANTOS_LAUDES_DEFEATED"] = "boss_laudes",
        ["D07Z01S02_BOSSDEAD"] = "boss_escribar",
        ["D20Z02S08_BOSSDEAD"] = "boss_sierpes",
        ["D01BZ08S01_BOSSDEAD"] = "boss_isidora",
        ["SANTOS_FIRSTCONVERSATION_DONE"] = "jibrael",
        ["SANTOS_AMANECIDA_LOCATION1_ACTIVATED"] = "openama2",
        ["SANTOS_AMANECIDA_LOCATION2_ACTIVATED"] = "openama1",
        ["SANTOS_AMANECIDA_LOCATION3_ACTIVATED"] = "openama3",
        ["SANTOS_AMANECIDA_LOCATION4_ACTIVATED"] = "openama4",
        ["PENITENT_MET_CLEOFAS"] = "talkcleofas",
        ["SERENO_DLC2QUEST_FINISHED"] = "loudghost",
        ["SOCORRO_STATE_GONE"] = "savesocorro",
        
    }
    
    trackedConsumables = {
        ["RB20"] = "toes",
        ["RB21"] = "toes",
        ["RB22"] = "toes",
        ["QI02"] = "refuge",
        ["QI03"] = "refuge",
        ["QI04"] = "refuge",
        ["QI06"] = "tentudia",
        ["QI07"] = "tentudia",
        ["QI08"] = "tentudia",
        ["QI10"] = "scorned",
        ["QI11"] = "scorned",
        ["QI12"] = "scorned",
        ["QI19"] = "herbs",
        ["QI20"] = "herbs",
        ["QI37"] = "herbs",
        ["QI63"] = "herbs",
        ["QI64"] = "herbs",
        ["QI65"] = "herbs",
        ["QI38"] = "wounds",
        ["QI39"] = "wounds",
        ["QI40"] = "wounds",
        ["QI60"] = "masks",
        ["QI61"] = "masks",
        ["QI62"] = "masks",
        ["QI107"] = "verses",
        ["QI108"] = "verses",
        ["QI109"] = "verses",
        ["QI110"] = "verses",
        ["QI201"] = "eyes",
        ["QI202"] = "eyes",
        ["CO01"] = "bones",
        ["CO02"] = "bones",
        ["CO03"] = "bones",
        ["CO04"] = "bones",
        ["CO05"] = "bones",
        ["CO06"] = "bones",
        ["CO07"] = "bones",
        ["CO08"] = "bones",
        ["CO09"] = "bones",
        ["CO10"] = "bones",
        ["CO11"] = "bones",
        ["CO12"] = "bones",
        ["CO13"] = "bones",
        ["CO14"] = "bones",
        ["CO15"] = "bones",
        ["CO16"] = "bones",
        ["CO17"] = "bones",
        ["CO18"] = "bones",
        ["CO19"] = "bones",
        ["CO20"] = "bones",
        ["CO21"] = "bones",
        ["CO22"] = "bones",
        ["CO23"] = "bones",
        ["CO24"] = "bones",
        ["CO25"] = "bones",
        ["CO26"] = "bones",
        ["CO27"] = "bones",
        ["CO28"] = "bones",
        ["CO29"] = "bones",
        ["CO30"] = "bones",
        ["CO31"] = "bones",
        ["CO32"] = "bones",
        ["CO33"] = "bones",
        ["CO34"] = "bones",
        ["CO35"] = "bones",
        ["CO36"] = "bones",
        ["CO37"] = "bones",
        ["CO38"] = "bones",
        ["CO39"] = "bones",
        ["CO40"] = "bones",
        ["CO41"] = "bones",
        ["CO42"] = "bones",
        ["CO43"] = "bones",
        ["CO44"] = "bones",
        ["CH01"] = "cherubs",
        ["CH02"] = "cherubs",
        ["CH03"] = "cherubs",
        ["CH04"] = "cherubs",
        ["CH05"] = "cherubs",
        ["CH06"] = "cherubs",
        ["CH07"] = "cherubs",
        ["CH08"] = "cherubs",
        ["CH09"] = "cherubs",
        ["CH10"] = "cherubs",
        ["CH11"] = "cherubs",
        ["CH12"] = "cherubs",
        ["CH13"] = "cherubs",
        ["CH14"] = "cherubs",
        ["CH15"] = "cherubs",
        ["CH16"] = "cherubs",
        ["CH17"] = "cherubs",
        ["CH18"] = "cherubs",
        ["CH19"] = "cherubs",
        ["CH20"] = "cherubs",
        ["CH21"] = "cherubs",
        ["CH22"] = "cherubs",
        ["CH23"] = "cherubs",
        ["CH24"] = "cherubs",
        ["CH25"] = "cherubs",
        ["CH26"] = "cherubs",
        ["CH27"] = "cherubs",
        ["CH28"] = "cherubs",
        ["CH29"] = "cherubs",
        ["CH30"] = "cherubs",
        ["CH31"] = "cherubs",
        ["CH32"] = "cherubs",
        ["CH33"] = "cherubs",
        ["CH34"] = "cherubs",
        ["CH35"] = "cherubs",
        ["CH36"] = "cherubs",
        ["CH37"] = "cherubs",
        ["CH38"] = "cherubs",
        --hosted consumables
        ["REDENTO_0203_DONE"] = "redento",
        ["REDENTO_0205_DONE"] = "redento",
        ["REDENTO_0207_DONE"] = "redento",
        ["REDENTO_0210_DONE"] = "redento",
        ["@QI57"] = "thimble",
        ["MIRIAM_FIRSTENCOUNTER_DONE"] = "miriam",
        ["RMIRIAM_D02Z03S24"] = "miriam",
        ["RMIRIAM_D03Z03S19"] = "miriam",
        ["RMIRIAM_D04Z04S02"] = "miriam",
        ["RMIRIAM_D05Z01S24"] = "miriam",
        ["RMIRIAM_D06Z01S26"] = "miriam",
        ["MEACULPA"] = "shrine",
       
        
           
    }
    
    trackedProgressives = {
        ["RB17"] = "red_wax",
        ["RB18"] = "red_wax",
        ["RB19"] = "red_wax",
        ["RB24"] = "blue_wax",
        ["RB25"] = "blue_wax",
        ["RB26"] = "blue_wax",
        ["QI13"] = "egg",
        ["QI14"] = "egg",
        ["QI59"] = "thimble",
        ["QI57"] = "thimble",
    }
    
    trackedLocations = {
        --Albero (35)
        ["@RB01"] = "Tirso's Attic/Albero Rosary",
        ["@CO43"] = "Warden of the Ossuary/Item Outside Door",
        ["@CO16"] = "Albero Graveyard/Albero Bone",
        ["@QI65"] = "Thyme/Acessible from another portal",
        ["@RESCUED_CHERUB_08"] = "Albero Cherub/Take the elevator down, use a prayer, or get the timing on that jump perfect and FREE HIM",
        ["@RE04"] = "Blessed Lord of the Salty Shores/Trade Shroud",
        ["@RE10"] = "Blessed Lord of the Salty Shores/Trade Hatched Egg",
        ["@RE02"] = "Blessed Lord of the Salty Shores/Trade Severed Hand",
        ["@QI01"] = "Lvdovico/Talk to Lvdovico after meeting Cleofas",
        ["@PR11"] = "The Church/Cleofas Finale",
        ["@QI66"] = "Tirso of the Wound Kissers/Herb Trade 1",
        ["@Tirso[500]"] = "Tirso of the Wound Kissers/Herb Trade 2",
        ["@Tirso[1000]"] = "Tirso of the Wound Kissers/Herb Trade 3",
        ["@Tirso[2000]"] = "Tirso of the Wound Kissers/Herb Trade 4",
        ["@Tirso[5000]"] = "Tirso of the Wound Kissers/Herb Trade 5",
        ["@Tirso[10000]"] = "Tirso of the Wound Kissers/Herb Trade 6",
        ["@QI56"] = "Tirso of the Wound Kissers/Defeat Exposito, Melquiades, and Quirce",
        ["@Lvdovico[500]"] = "Lvdovico/Trade Tentudia's Carnal Remains",
        ["@Lvdovico[1000]"] = "Lvdovico/Trade Remains of Tentudia's Hair",
        ["@PR03"] = "Lvdovico/Trade Tentudia's Skeletal Remains", 
        ["@QI201"] = "Warden of the Ossuary/Open path to Isidora",
        ["@Sword[D01Z02S06]"] = "Mea Culpa Shrine #1/free check",    
        ["@RB104"] = "The Church/Donate $5,000",
        ["@RB105"] = "The Church/Donate $50,000",
        ["@Undertaker[250]"] = "Warden of the Ossuary/4 Bones Reward",
        ["@Undertaker[500]"] = "Warden of the Ossuary/8 Bones Reward",
        ["@Undertaker[750]"] = "Warden of the Ossuary/12 Bones Reward",
        ["@Undertaker[1000]"] = "Warden of the Ossuary/16 Bones Reward",
        ["@Undertaker[1250]"] = "Warden of the Ossuary/20 Bones Reward",
        ["@Undertaker[1500]"] = "Warden of the Ossuary/24 Bones Reward",
        ["@Undertaker[1750]"] = "Warden of the Ossuary/28 Bones Reward",
        ["@Undertaker[2000]"] = "Warden of the Ossuary/32 Bones Reward",
        ["@Undertaker[2500]"] = "Warden of the Ossuary/36 Bones Reward",
        ["@Undertaker[3000]"] = "Warden of the Ossuary/40 Bones Reward",
        ["@Undertaker[5000]"] = "Warden of the Ossuary/44 Bones Reward",
        --miriam
        ["@MIRIAM_FIRSTENCOUNTER_DONE"] = "Miriam/Talk to her to start the quest",
        ["@PR201"] = "Miriam/Finish all five challenge rooms to send her home",
        
        -- rooftops
        ["@QI02"] = "AR: First soldier fight/Mark of the First Refuge",
        ["@QI03"] = "AR: Second soldier fight/Mark of the Second Refuge",
        ["@QI04"] = "AR: Third soldier fight/Mark of the Third Refuge",
        ["@CO06"] = "AR: Upper west shaft ledge/Archcathedral Bone 1",
        ["@RESCUED_CHERUB_36"] = "AR: Upper west shaft Child of Moonlight/FREE HIM",
        ["@PR12"] = "AR: Upper west shaft chest/Archcathedral Prayer",
        ["@HE04"] = "AR: Statue near MoM/Archcathedral Heart",
        ["@Lady[D06Z01S24]"] = "AR: Lady of the Six Sorrows/Archcathedral HP+",
        ["@CO40"] = "AR: Upper east shaft ledge/Archcathedral Bone 2",
        ["@Sword[D06Z01S11]"] = "Mea Culpa Shrine #6/Unlock gate getting check below",
        ["@BS16"] = "Crisanta of the Wrapped Agony/Defeat Crisanta",
        ["@HE101"] = "BotTC: Inside giant statue/Bridge Heart",
        ["@PR08"] = "Crisanta of the Wrapped Agony/Viridiana's Prayer",
        ["@SANTOS_AMANECIDA_LOCATION3_ACTIVATED"] = "The Once Forbidden Rooftops/Jibrael on the Rooftops",
        ["@RMIRIAM_D06Z01S26"] = "Rooftops Miriam Gate/Good luck!",
        -- bridge
        ["@BS12"] = "Proof of Humiliations/Defeat Esdras",
        --hall checks
        ["@LaudesBossTrigger[30000]"] = "Laudes, First of the Amanecidas/Also the last",
        ["@QI105"] = "HotD: Mirror room/Hall Quicksilver Check",
        --Brotherhood
        ["@RESCUED_CHERUB_06"] = "BotSS: Starting room Child of Moonlight/FREE HIM",
       --["REDENTO_0207_DONE"] = "Brotherhood Maze Door/Clear a path for Redento",
        ["@RB204"] = "BotSS: Starting room ledge/Brotherhood Rosary",
        ["@RE01"] = "BotSS: Chamber of the Eldest Brother/GET OUT OF MY ROOM",
        ["@Sword[D17Z01S08]"] = "Mea Culpa Shrine #2/free check",
        ["@CO25"] = "Brotherhood Maze Door/Bone",
        ["CANDLE_BLUE_1_USED"] = "Brotherhood Maze Door/Blue Candle",
        ["@REDENTO_0207_DONE"] = "Brotherhood Maze Door/Clear a path for Redento",
        ["@PR203"] = "Brotherhood Prayer/This Blood Was Made For Walkin'",
        ["@QI204"] = "Hidden Brotherhood Church/Bring the Incomplete Scapular after defeating Esdras",
        ["@QI301"] = "Hidden Brotherhood Church/Reward for sparing Crisanta",
        ["@BS13"] = "Defeat the Warden of the Silent Sorrow/Start the game",
        ["CONFESSOR_4_ARENACOMPLETED"] = "Brotherhood Confessor/BREAK IT",
        -- convent
        ["@CO05"] = "CoOLotCV: Snowy window ledge/Convent Bone 2",
        ["@CO15"] = "CoOLotCV: Center enemy lineup/Convent Bone 1",
        ["@RB08"] = "CoOLotCV: Center miasma room/Convent Rosary",
        ["@HE03"] = "Convent Heart/Possible damage run",
        ["@Lady[D02Z03S15]"] = "CoOLotCV: Lady of the Six Sorrows/Convent HP+",
        ["@Sword[D02Z03S13]"] = "Mea Culpa Shrine #3/free check",
        ["CANDLE_RED_1_USED"] = "CoOLotCV: Red candle/Red Candle in the Convent",
        ["@RB24"] = "CoOLotCV: Blue candle/Blue Candle #1",
        ["@RB107"] = "CoOLotCV: Outside pathway/Convent Rosary 2",
        ["@QI57"] = "Hot Oil Basin/filler up",
        ["@BS03"] = "CoOLotCV: Our Lady of the Charred Visage/Charred Visage Check",
        ["@QI40"] = "Visage of Compunction/you did it!",
        ["@QI61"] = "CoOLotCV: Mask room/Mirrored Mask of Dolphos",
        ["@SANTOS_AMANECIDA_LOCATION2_ACTIVATED"] = "Jibrael in Convent/Reveal Graveyard Amanecida",
        ["@RMIRIAM_D02Z03S24"] = "Convent Miriam Gate/Good luck!",
        --cistern
        ["@Lady[D01Z05S22]"] = "DC: Lady of the Six Sorrows, from MD/Cistern HP+ 1",
        ["@CO41"] = "DC: Behind sewage drips/Cistern Bone 2",
        ["@RESCUED_CHERUB_11"] = "Cistern Cherub 3/FREE HIM",
        ["@QI45"] = "DC: Lower east tunnel chest/Cistern Bile Flask",
        ["@PR16"] = "DC: Upper east tunnel chest/Cistern Prayer",
        ["@RESCUED_CHERUB_13"] = "Cistern Cherub 1/FREE HIM",
        ["@QI67"] = "DC: Hidden alcove near fountain/Severed Hand Check",
        ["@CO09"] = "DC: Shortcut to WotBC/Cistern Bone 1",
        ["@Oil[D01Z05S07]"] = "DC: Oil of the Pilgrims/Cistern MP+",
        ["@RESCUED_CHERUB_14"] = "Cistern Cherub 2/FREE HIM",
        ["@QI12"] = "DC: Behind gate in miasma room/Black Grieving Veil",
        ["@RESCUED_CHERUB_12"] = "Cistern Cherub 4/FREE HIM",
        ["@CO32"] = "DC: High ledge near elevator shaft/Cistern Bone 3",
        ["@RB03"] = "Number Room/Equip shroud, leaving and coming back changes the numbers on each side. Set it to IV and II",
        ["@QI75"] = "Chalice Quest/google blasphemous chalice quest, it fuckin sucks tbh",
        ["@Sword[D01Z05S24]"] = "Mea Culpa Shrine #7/free check",
        ["@Lady[D01Z05S26]"] = "DC: Lady of the Six Sorrows, elevator shaft/Cistern HP+ 2",
        ["@RESCUED_CHERUB_15"] = "Cistern Cherub 6/FREE HIM",
        ["@RESCUED_CHERUB_22"] = "Cistern Cherub 5/FREE HIM",
        ["@CO44"] = "DC: Elevator shaft ledge/Cistern Bone 4",
        --echoes
        ["@RB108"] = "EoS: Lantern jump near MotED/Echoes Rosary 1",
        ["@RB202"] = "EoS: Lantern jump near elevator/Echoes Rosary 2",
        ["@SANTOS_AMANECIDA_LOCATION1_ACTIVATED"] = "Jibrael in Echoes/Reveal Jondo Amanecida",
        --graveyard
        ["@RESCUED_CHERUB_31"] = "Graveyard Cherub 1/FREE HIM",
        ["@CO42"] = "Graveyard Bone 1/Break the floor",
        ["@QI11"] = "Graveyard Shop/Plate 1",
        ["@RB37"] = "Graveyard Shop/Plate 2",
        ["@RB02"] = "Graveyard Shop/Plate 3",
        ["@RB38"] = "Graveyard Confessor/free check",
        ["@RESCUED_CHERUB_26"] = "Graveyard Cherub 4/FREE HIM",
        ["@QI53"] = "GotP: Elevator shaft ledge/Graveyard Rosary Knot",
        ["@Lady[D02Z02S12]"] = "GotP: Lady of the Six Sorrows/Graveyard HP+",
        ["@HE11"] = "Graveyard Heart/You gotta cut yourself D:",
        ["@QI46"] = "GotP: Lower east shaft/Graveyard Bile Flask",
        ["@CO29"] = "GotP: Center east shaft/Graveyard Bone 2",
        ["@QI08"] = "GA: End of blood bridge/Tentudia's Skeletal Remains",
        ["@RB106"] = "It's such a specific jump you might wanna look it up tbh/Graveyard Rosary 2",
        ["@RESCUED_CHERUB_25"] = "Graveyard Cherub 3/FREE HIM",
        ["@RB32"] = "GotP: Lower west shaft/Graveyard Rosary 1",
        ["@CO01"] = "GotP: Upper west shaft/Graveyard Bone 3",
        ["@RESCUED_CHERUB_24"] = "Graveyard Cherub 2/FREE HIM",
        ["@RB15"] = "GotP: Center shaft ledge/Graveyard Rosary 3",
        ["@Oil[D02Z02S10]"] = "GotP: Oil of the Pilgrims/Graveyard MP+",
        ["CONFESSOR_2_ARENACOMPLETED"] = "Graveyard Confessor/BREAK IT",
        ["@D02Z02S14[18000]"] = "It's such a specific jump you might wanna look it up tbh/Amanecida of the Bejeweled Arrow",
        -- grievance
        ["@QI44"] = "GA: Lower west ledge/Grievance Rosary Knot",
        ["@RE07"] = "Lung and Cherub/Lung",
        ["@RESCUED_CHERUB_19"] = "Lung and Cherub/FREE HIM",
        ["@CO12"] = "GA: Miasma room floor/Grievance Bone",
        ["@Oil[D03Z03S13]"] = "GA: Oil of the Pilgrims/Grievance MP+",  
        ["@QI10"] = "Melted Coins and Cherub/Melted Coins",
        ["@RESCUED_CHERUB_21"] = "Melted Coins and Cherub/FREE HIM",
        ["@RESCUED_CHERUB_20"] = "Grievance Cherub 3/FREE HIM",
        ["@QI13"] = "Altasgracias/Leave the three offerings",
        ["@RB06"] = "Altasgracias/Come back once the egg is hatched",
        ["@BS04"] = "GA: Tres Angustias/woah triplets eyes emoji",
        ["@QI39"] = "GA: Visage of Contrition/aw nice good job",
        ["CONFESSOR_3_ARENACOMPLETED"] = "Grievance Ascends Confessor/BREAK IT",
        ["@RMIRIAM_D03Z03S19"] = "Grievance Miriam Gate/Good luck!",
        -- jondo
        ["@CO08"] = "Jondo: Upper east ledge/Jondo Bone 1",
        ["@PR10"] = "Jondo Prayer/CLIMB",
        ["@CO33"] = "Jondo: Lower east under chargers/Jondo Bone 3",
        ["@QI19"] = "Jondo: Lower east bell trap/Bouquet of Rosemary",
        ["@RESCUED_CHERUB_18"] = "Jondo Cherub 2/FREE HIM",
        ["@RESCUED_CHERUB_37"] = "Jondo: Spike tunnel Child of Moonlight/FREE HIM",
        ["@HE06"] = "Jondo: Spike tunnel statue/Jondo Heart",
        ["@QI103"] = "Jondo: Spike tunnel cave/Jondo Quicksilver",
        ["@CO07"] = "Jondo: Lower west lift alcove/Jondo Bone 2",
        ["@QI41"] = "Jondo: Lower west bell alcove/Jondo Bile Flask",
        ["@QI52"] = "Jondo: Upper west bell puzzle/Jondo Rosary Knot",
        ["@RB28"] = "Jondo: Upper west tree root/Jondo Rosary",
        ["@RESCUED_CHERUB_17"] = "Jondo Cherub 1/FREE HIM",
        ["@BELL_PUZZLE1_ACTIVATED"] = "Jondo Statue #1/Break for GA access",
        ["@BELL_PUZZLE2_ACTIVATED"] = "Jondo Statue #2/Break for GA access",
        ["@BELL_ACTIVATED"] = "Jondo Bell for GA access/ring for GA access",
        --mothers
        ["@HE201"] = "The Fourth Visage/return his dang EYES",
        --library
        ["@RESCUED_CHERUB_01"] = "Library Cherub 2/FREE HIM",
        ["@CO18"] = "LotNW: Platform room ledge/Library Bone 2",
        ["@CO22"] = "LotNW: Root ceiling platform/Library Bone 1",
        ["@QI50"] = "LotNW: Hidden floor/Smash the floor",
        ["@RB31"] = "LotNW: Miasma hallway chest/Library Rosary 2",
        ["@Lady[D05Z01S14]"] = "LotNW: Lady of the Six Sorrows/Library HP+",
        ["@PR15"] = "LotNW: Bone puzzle/Fill fervor bar, unequip everything, and stand still",
        ["@CO28"] = "LotNW: Lowest west upper ledge/Library Bone 3",
        ["@Sword[D05Z01S13]"] = "Mea Culpa Shrine #4/free check",
        ["@PR07"] = "LotNW: Platform puzzle chest/Library Prayer",
        ["@RB30"] = "LotNW: Lowest west center ledge/Library Rosary 1",
        ["@RESCUED_CHERUB_02"] = "Library Cherub 1/FREE HIM",
        ["@Oil[D05Z01S19]"] = "LotNW: Oil of the Pilgrims/Library MP+",
        ["@RESCUED_CHERUB_32"] = "Library Cherub 3/FREE HIM",
        ["@CANDLE_RED_2_USED"] = "LotNW: Red candle/Red Candle in the Library",
        ["@QI62"] = "LotNW: Mask room/Embossed Mask of Crescente",
        ["@RMIRIAM_D05Z01S24"] = "Library Miriam Gate/Good luck!",
        ["@RB19"] = "LotNW: Red candle/Red Candle #3",
        ["@RB203"] = "Diosdado 1/Kill the ghost, go in, come out",
        ["@RB301"] = "Diosdado 2/Breakable left wall inside the door",
        ["CONFESSOR_6_ARENACOMPLETED"] = "Library Confessor/BREAK IT",
        --mercy dreams
        ["@CO30"] = "MD: First area hidden wall/Mercy Dreams Bone 1",
        ["@PR01"] = "MD: Second area trapped chest/Mercy Dreams Prayer",
        ["@CO03"] = "MD: Second area ledge/Mercy Dreams Bone 2",
        ["@RESCUED_CHERUB_09"] = "Mercy Dreams Cherub/FREE HIM",
        ["@RB17"] = "MD: Red candle/Red Candle #1",
        ["@QI58"] = "Mercy Dreams Shop/Plate 1",
        ["@RB05"] = "Mercy Dreams Shop/Plate 2",
        ["@RB09"] = "Mercy Dreams Shop/Plate 3",
        ["@QI48"] = "MD: Third area hidden room/Mercy Bile Flask",
        ["@CO38"] = "MD: Sliding challenge/Mercy Dreams Bone 4",
        ["@BS01"] = "MD: Ten Piedad/half man part party animal",
        ["@QI38"] = "MD: Visage of Attrition/More like Ten PieDEAD",
        ["CANDLE_BLUE_2_USED"] = "Blue Candle Room/MD: Blue candle",
        ["@RESCUED_CHERUB_33"] = "Blue Candle Room/FREE HIM",
        ["@CO21"] = "MD: Behind gate to TSC/Mercy Dreams Bone 3",
        ["CONFESSOR_1_ARENACOMPLETED"] = "Mercy Dreams Confessor/BREAK IT",
        --mothers
        ["@Oil[D04Z02S14]"] = "MoM: Oil of the Pilgrims/Mothers MP+",
        ["@RB33"] = "MoM: Upper east ledge/Mothers Rosary",
        ["@CO35"] = "MoM: East chandelier platform/Mothers Bone 4",
        ["@RESCUED_CHERUB_30"] = "Mothers Cherub 1/FREE HIM",
        ["@CO17"] = "MoM: Upper west floor/Mothers Bone 1",
        ["@RE03"] = "MoM: Final meeting with Redento/Equip all three toe rosaries and let Redento rest",
        ["@QI54"] = "MoM: Final meeting with Redento/Leave and come back",
        ["@HE01"] = "MoM: Giant chandelier statue/Mothers Heart",
        ["@PENITENT_MET_CLEOFAS"] = "Cleofas Quest/Talk to Cleofas",
        ["@SOCORRO_STATE_GONE"] = "Cleofas Quest/Give Socorro the Three Marks of the Refuge",
        ["@CO34"] = "MoM: Outside Cleofas' room/Mothers Bone 3",
        ["@CO20"] = "MoM: Upper center floor/Mothers Bone 2",
        ["@RESCUED_CHERUB_29"] = "Mothers Cherub 2/FREE HIM",
        ["@Sword[D04Z02S12]"] = "Mea Culpa Shrine #5/free check",
        ["@BS05"] = "MoM: Melquiades, The Exhumed Archbishop/catch these hands",
        ["@QI60"] = "MoM: Mask room/Deformed Mask of Orestes",
        ["CONFESSOR_5_ARENACOMPLETED"] = "Mother of Mothers Confessor/BREAK IT",
        ["@RMIRIAM_D04Z04S02"] = "Mothers Miriam Gate/Good luck!",
        
        --mountains
        ["@CO13"] = "MotED: Under entrance to DC/Mountain Bone",
        ["@RB13"] = "Tree Offering/Beat Perpetva",
        ["@RESCUED_CHERUB_16"] = "Mountain Cherub/FREE HIM",
        ["@QI47"] = "Center Stage/upper flask",
        ["@REDENTO_0203_DONE"] = "MotED: 1st meeting with Redento/Get the platforms moving for Redento",
        ["@QI63"] = "MotED: Blood platform alcove/Clove Check",
        ["@QI14"] = "Tree Offering/Lay an Egg",
        ["@D03Z01S03[18000]"] = "Center Stage/Amanecida of the Golden Blades",
        -- mourning
        ["@PR202"] = "MaH: West chest/Mourning Prayer West",
        ["@RB201"] = "MaH: Upper east chest/Mourning Prayer East",
        ["@QI202"] = "MaH: Sierpes/Double Pr-eye-zes",
        -- patio
        ["@RESCUED_CHERUB_35"] = "Patio Cherub 1/FREE HIM",
        ["@CO23"] = "PotSS: First area ledge/Patio Bone 1",
        ["@RB14"] = "PotSS: Second area ledge/Patio Rosary",
        ["@RESCUED_CHERUB_28"] = "Patio Cherub 2/FREE HIM",
        ["@QI37"] = "Bone and Seed/Patio Bone 2",
        ["@CO39"] = "Bone and Seed/Olive Seeds",
        ["@QI102"] = "PotSS: Climb to WotHP/Can also be grabbed from prison exit without relics",
        ["@REDENTO_0210_DONE"] = "PotSS: 4th meeting with Redento/Kill that big freak for Redento",
        --["@RB21"] = "PotSS: 4th meeting with Redento/Kill that big freak for Redento",
        ["@D04Z01S04[18000]"] = "PotSS: Amanecida of the Chiselled Steel/PotSS: Amanecida of the Chiselled Steel",
        --petrous
        ["@QI101"] = "Welcome 2 Petrous/Free standing check",
        ["@SANTOS_FIRSTCONVERSATION_DONE"] = "Welcome 2 Petrous/Start Jibrael quest",
        
        --resting place 
        ["@QI203"] = "TRPotS: Perpetva's shrine/Resting Place of the Sister",
        --sleeping canvases
        ["@QI64"] = "TSC: Painting ladder ledge/Sooty Garlic",
        ["@HE07"] = "TSC: Candle wax puzzle/equip big beads of red and blue wax, cut yourself in the middle of the room",
        ["@RB12"] = "Canvases Shop/Plate 1",
        ["@QI49"] = "Canvases Shop/Plate 2",
        ["@QI71"] = "Canvases Shop/Plate 3",
        ["@QI104"] = "TSC: Swinging blade tunnel/Canvases Quicksilver",
        ["@BS06"] = "TSC: Exposito, Scion of Abjuration/will SOMEbody SHUT that BABY UP",
        ["@CO31"] = "TSC: Under elevator shaft/Canvases Bone",
        ["@RE05"] = "Jocinero, Child of Moonlight/20 Cherub Reward",
        ["@PR05"] = "Jocinero, Child of Moonlight/38 Cherub Reward",
        --the holy line 
        ["@QI31"] = "THL: Deogracias' gift/Free Thorn",
        ["@PR14"] = "THL: Hanging skeleton/Free Stuff",
        ["@RB07"] = "THL: Across blood platforms/Jump that blood baby",
        ["@RESCUED_CHERUB_07"] = "Holy Line Cherub/FREE HIM",
        ["@CO04"] = "Underground Bone/Jump from high up to break through",
        ["@QI55"] = "THL: Underground chest/it's muddy and it's bloody",
        -- wall of holy prohibitions
        ["@RB11"] = "WotHP: Upper east room, lift puzzle/Move the elevator 6 times",
        ["@CO10"] = "WotHP: Upper east room, center cell floor/Ledge check",
        ["@QI69"] = "WotHP: Upper east room, center cell floor/You'll have to save and quit if you dont have Key of the Secular",
        ["@RESCUED_CHERUB_03"] = "WotHP: Upper east room, top bronze cell/FREE HIM",
        ["@CO24"] = "WotHP: Upper east room, top silver cell/Prohibitions Bone 4",
        ["@QI51"] = "WotHP: Upper east room, center gold cell/Prohibitions Bile Flask",
        ["@CO26"] = "WotHP: Upper west room, center gold cell/Another bone check idk",
        ["@CO02"] = "WotHP: Lower west room, bottom gold cell/Break the wall",
        ["@RESCUED_CHERUB_34"] = "Quirce Room/FREE HIM",
        ["@RB16"] = "Jibby's cell/Outside the cell",
        ["@SANTOS_AMANECIDA_LOCATION4_ACTIVATED"] = "Jibby's cell/Jibrael in Jail",
        ["@CO27"] = "WotHP: Lower east room, hidden ledge/Break the wall",
        ["@RESCUED_CHERUB_04"] = "Lower east room, bottom silver cell/FREE HIM",
        ["@QI70"] = "WotHP: Lower east room, top bronze cell/Scribe key check",
        ["@CO37"] = "WotHP: Lower east room, top silver cell/Prohibitions Bone 5",
        ["@RESCUED_CHERUB_05"] = "WotHP: Outside Child of Moonlight/FREE HIM",
        ["@Oil[D09Z01S12]"] = "WotHP: Oil of the Pilgrims/go up through scribe key door down and to the right from here, then break the wall",
        ["@BS14"] = "Quirce Room/Defeat Quirce",
        ["@QI72"] = "Quirce Room/Come back for the check after you beat Quirce",
        ["@D09Z01S01[18000]"] = "WotHP: Amanecida of the Molten Thorn/Amanecida of the Molten Thorn",
        ["CONFESSOR_7_ARENACOMPLETED"] = "Wall of Prohibitions Confessor/BREAK IT",
        -- wasteland
        ["@RB04"] = "WotBC: Lower log path/Wasteland Rosary",
        ["@CO14"] = "WotBC: Hidden alcove/Wasteland Bone 1",
        ["@CO36"] = "WotBC: Outside ledge/Wasteland Bone 2",
        ["@RESCUED_CHERUB_10"] = "Wasteland Cherub/FREE HIM",
        ["@QI06"] = "WotBC: Under broken bridge/Tentudia's Carnal Remains",
        ["@HE02"] = "Wasteland Heart+Cherub/Heart statue",
        ["@RESCUED_CHERUB_38"] = "Wasteland Heart+Cherub/FREE HIM",
       ["@REDENTO_0205_DONE"] = "WotBC: 3rd meeting with Redento/Knock down some trees for Redento",
        -- where they be withering at   
        ["@CO11"] = "WOTW: Below Prie Dieu/Wither Bone 1",
        ["@QI20"] = "WOTW: Entrance to tomb/Incense Garlic",
        ["@QI68"] = "Gemino's Cave/in his hand",
        ["@PR04"] = "WOTW: Underground tomb/Leave the flowers",
        ["@RESCUED_CHERUB_27"] = "Wither Cherub 1/fall from above with linen AND FREE HIM",
        ["@CO19"] = "WOTW: Underground ledge/Wither Bone 2",
        ["@RESCUED_CHERUB_23"] = "Wither Cherub 2/FREE HIM",
        ["@HE05"] = "WOTW: Upper east statue/Wither Heart",
        ["@QI07"] = "WOTW: Death run/Remains of Tentudia's Hair",
        ["@QI59"] = "Gemino/Gemino's gift",
        ["@RB10"] = "Gemino's Hot Oil Rub/Trade Filled Thimble, leave him and come back or pick up the same check in his cave",
        --shrines       
        ["@COMBO_1"] = "Shrine Skill Shop/Tier 1 Item 1",
        ["@COMBO_2"] = "Shrine Skill Shop/Tier 2 Item 1",
        ["@COMBO_3"] = "Shrine Skill Shop/Tier 4 Item 1",
        ["@CHARGED_1"] = "Shrine Skill Shop/Tier 1 Item 2",
        ["@CHARGED_2"] = "Shrine Skill Shop/Tier 3 Item 1",
        ["@CHARGED_3"] = "Shrine Skill Shop/Tier 6 Item 1",
        ["@RANGED_1"] = "Shrine Skill Shop/Tier 2 Item 2",
        ["@RANGED_2"] = "Shrine Skill Shop/Tier 5 Item 1",
        ["@RANGED_3"] = "Shrine Skill Shop/Tier 7 Item 1",
        ["@VERTICAL_1"] = "Shrine Skill Shop/Tier 1 Item 3",
        ["@VERTICAL_2"] = "Shrine Skill Shop/Tier 3 Item 2",
        ["@VERTICAL_3"] = "Shrine Skill Shop/Tier 6 Item 2",
        ["@LUNGE_1"] = "Shrine Skill Shop/Tier 1 Item 4",
        ["@LUNGE_2"] = "Shrine Skill Shop/Tier 2 Item 3",
        ["@LUNGE_3"] = "Shrine Skill Shop/Tier 4 Item 2",
    }
    
    
    function updateToggles(store, vars)
        print("updateToggles") 
        for _, var in ipairs(vars) do
            local o = Tracker:FindObjectForCode(trackedToggles[var])
            local val = store:ReadVariable(var)
            o.Active = true
        end
    end
    
    
    function updateConsumables(store, vars)
        print("updateConsumables") 
        for _, var in ipairs(vars) do
            local o = Tracker:FindObjectForCode(trackedConsumables[var])
            local val = store:ReadVariable(var)
            o.AcquiredCount = o.AcquiredCount + 1
        end
    end
    
    
    function updateProgressiveToggles(store, vars)
        print("updateProgressiveToggles") 
        for _, var in ipairs(vars) do
            local o = Tracker:FindObjectForCode(trackedProgressives[var])
            local val = store:ReadVariable(var)
            o.CurrentStage = o.CurrentStage + 1
            o.Active = true
        end
    end
    
    
    function updateLocations(store, vars)
        print("updateLocations") 
        for _, var in ipairs(vars) do
            local o = Tracker:FindObjectForCode("@"..trackedLocations[var])
            local val = store:ReadVariable(var)
            o.AvailableChestCount = o.AvailableChestCount - 1
        end
    end
    
    if location_name == "Jondo Statue #1/Break for GA access" then
        Tracker:FindObjectForCode("statue1").Active = true
    end
    if location_name == "Jondo Statue #2/Break for GA access" then
        Tracker:FindObjectForCode("statue2").Active = true
    end
    if location_name == "REDENTO_0207_DONE" then
        Tracker:FindObjectForCode("redento").Active = true
    end
    for gameVar, trackerVar in pairs(trackedToggles) do
        ScriptHost:AddVariableWatch(gameVar, { gameVar }, updateToggles)
    end
    for gameVar, trackerVar in pairs(trackedConsumables) do
        ScriptHost:AddVariableWatch(gameVar, { gameVar }, updateConsumables)
    end
    for gameVar, trackerVar in pairs(trackedProgressives) do
        ScriptHost:AddVariableWatch(gameVar, { gameVar }, updateProgressiveToggles)
    end
    for gameVar, trackerVar in pairs(trackedLocations) do
        ScriptHost:AddVariableWatch(gameVar, { gameVar }, updateLocations)
    end
    
    print("added UAT callbacks")